# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: EshopWeb

stages:
  - stage: BuildStage
    displayName: "BuildStage"
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: 'restore'
              projects: '**/ApplicationCore.csproj'
              feedsToUse: 'select'

          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: 'build'
              projects: '**/ApplicationCore.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Unit Test'
            inputs:
              command: 'test'
              projects: '**/UnitTests.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Publish'
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '-o $(Build.ArtifactStagingDirectory)/ApplicationCore'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/ApplicationCore'
              artifact: 'RetailApp'

  - stage: Deploy
    jobs:
      - job: DevEnv
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'RetailApp'
              path: '$(Pipeline.Workspace)/RetailApp'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Free Trial(1)(3a373df8-1ae2-4620-8c66-0550ba56d571)'
              appType: 'webApp'
              WebAppName: 'webinfy'
              packageForLinux: '$(Pipeline.Workspace)/RetailApp/ApplicationCore.zip'

        # - task: AzureRmWebAppDeployment@4
        #   inputs:
        #       ConnectionType: 'AzureRM'
        #       azureSubscription: 'Free Trial(1)(3a373df8-1ae2-4620-8c66-0550ba56d571)'
        #       appType: 'webApp'
        #       WebAppName: 'webinfy'
        #       package: '$(Pipeline.Workspace)/RetailApp/**/*.zip'

# name: EshopWeb

# stages:
#   - stage: 'BuildStage'
#     displayName: "BuildStage"
#     jobs:
#       - job: 'BuildJob'
#         pool:
#           vmImage: 'windows-latest'
#         steps:
#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'restore'
#             projects: '**/ApplicationCore.csproj'
#             feedsToUse: 'select'
#           displayName: 'restore'

#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'build'
#             projects: '**/ApplicationCore.csproj'
#           displayName: 'Build'

#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'test'
#             projects: '**/UnitTests.csproj'
#           displayName: 'Unit-Test'

#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'publish'
#             publishWebProjects: true
#             arguments: '-o $(Build.ArtifactStagingDirectory)/ApplicationCore'
#           displayName: 'Publish'

#         - task: PublishPipelineArtifact@1
#           inputs:
#             targetPath: '$(Build.ArtifactStagingDirectory)/ApplicationCore'
#             artifact: 'RetailApp'
#           displayName: 'PublishArtifact'
            
#   - stage: Deploy
#     jobs:
#       - job: 'DevEnv'
#         pool:
#           vmImage: 'windows-latest'
#         steps:
#           - task: DownloadPipelineArtifact@2
#             inputs:
#               artifact: 'RetailApp'
#               path: '$(Pipeline.Workspace)/RetailApp'
              
#           - task: AzureRmWebAppDeployment@4
#             inputs:
#               ConnectionType: 'AzureRM'
#               azureSubscription: 'Free Trial(3a373df8-1ae2-4620-8c66-0550ba56d571)'
#               appType: 'webApp'
#               WebAppName: 'infyweb'
#               package: '$(Pipeline.Workspace)/RetailApp/**/ApplicationCore.zip'

        


# name: EshopWeb

# stages:
#   - stage: 'BuildStage'
#     displayName: "BuildStage"
#     jobs:
#       - job: 'BuildJob'
#         pool:
#           vmImage: 'windows-latest'
#         steps:
#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'restore'
#             projects: '**/ApplicationCore.csproj'
#             feedsToUse: 'select'
#           displayName: 'Restore'

#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'build'
#             projects: '**/ApplicationCore.csproj'
#           displayName: 'Build'

#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'test'
#             projects: '**/UnitTests.csproj'
#           displayName: 'Unit-Test'

#         - task: DotNetCoreCLI@2
#           inputs:
#             command: 'publish'
#             publishWebProjects: true
#             arguments: '-o $(Build.ArtifactStagingDirectory)/ApplicationCore'
#           displayName: 'Publish'

#         - script: |
#             echo "Listing files in $(Build.ArtifactStagingDirectory)/ApplicationCore:"
#             dir "$(Build.ArtifactStagingDirectory)/ApplicationCore"
#           displayName: 'List files after Publish'

#         - task: PublishPipelineArtifact@1
#           inputs:
#             targetPath: '$(Build.ArtifactStagingDirectory)/ApplicationCore'
#             artifact: 'RetailApp'
#           displayName: 'Publish Artifact'

#   - stage: Deploy
#     displayName: 'DeployStage'
#     jobs:
#       - job: 'DevEnv'
#         pool:
#           vmImage: 'windows-latest'
#         steps:
#           - task: DownloadPipelineArtifact@2
#             inputs:
#               artifact: 'RetailApp'
#               path: '$(Pipeline.Workspace)/RetailApp'

#           - script: |
#               echo "Listing files in $(Pipeline.Workspace)/RetailApp:"
#               dir "$(Pipeline.Workspace)/RetailApp"
#             displayName: 'List files in RetailApp'

#           - script: |
#               echo "Listing files in $(Pipeline.Workspace)/RetailApp/ApplicationCore:"
#               dir "$(Pipeline.Workspace)/RetailApp/ApplicationCore"
#             displayName: 'List files in ApplicationCore directory'

#           - task: AzureRmWebAppDeployment@4
#             inputs:
#               ConnectionType: 'AzureRM'
#               azureSubscription: 'Free Trial(3a373df8-1ae2-4620-8c66-0550ba56d571)'
#               appType: 'webApp'
#               WebAppName: 'infyweb'
#               package: '$(Pipeline.Workspace)/RetailApp/ApplicationCore/*.zip'
